# Generated by Django 2.2.25 on 2023-05-14 15:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Admin',
            fields=[
                ('notification_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=100)),
                ('password', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('appointment_id', models.AutoField(primary_key=True, serialize=False)),
                ('appointment_time', models.DateTimeField()),
                ('appointment_status', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='CarouselMap',
            fields=[
                ('carousel_map_id', models.AutoField(primary_key=True, serialize=False)),
                ('carousel_map_img', models.ImageField(upload_to='')),
                ('carousel_map_link', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Code',
            fields=[
                ('verification_code', models.CharField(max_length=20)),
                ('phone_number', models.BigIntegerField(primary_key=True, serialize=False)),
                ('create_time', models.DateTimeField()),
                ('expire_time', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Department',
            fields=[
                ('department_id', models.AutoField(primary_key=True, serialize=False)),
                ('department_name', models.CharField(max_length=20)),
                ('department_type', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Doctor',
            fields=[
                ('doctor_id', models.AutoField(primary_key=True, serialize=False)),
                ('phone_number', models.CharField(max_length=200)),
                ('doctor_name', models.CharField(max_length=200)),
                ('doctor_gender', models.CharField(max_length=200)),
                ('doctor_image', models.ImageField(default='', upload_to='')),
                ('doctor_introduction', models.CharField(max_length=200)),
                ('department_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hospitalManage.Department')),
            ],
        ),
        migrations.CreateModel(
            name='News',
            fields=[
                ('news_id', models.AutoField(primary_key=True, serialize=False)),
                ('news_title', models.CharField(max_length=200)),
                ('news_link', models.CharField(max_length=200)),
                ('news_date', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('notification_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('content', models.CharField(max_length=255)),
                ('title', models.CharField(max_length=200)),
                ('notification_time', models.DateField()),
                ('notification_link', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('user_id', models.AutoField(primary_key=True, serialize=False)),
                ('phone_number', models.CharField(max_length=200)),
                ('passwd', models.CharField(max_length=200)),
                ('avatar', models.ImageField(default='', upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='Vacancy_setting',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vacancy_cnt', models.IntegerField(default=10)),
                ('vacancy_day', models.IntegerField()),
                ('vacancy_time', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Vacancy',
            fields=[
                ('vacancy_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('vacancy_count', models.IntegerField(default=100)),
                ('vacancy_left', models.IntegerField(default=100)),
                ('start_time', models.DateTimeField()),
                ('end_time', models.DateTimeField()),
                ('doctor_id', models.ManyToManyField(to='hospitalManage.Doctor')),
            ],
        ),
        migrations.CreateModel(
            name='Schedule',
            fields=[
                ('schedule_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('schedule_day', models.DateField()),
                ('schedule_ismorning', models.IntegerField(default=0)),
                ('doctor_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hospitalManage.Doctor')),
            ],
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('payment_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('amount', models.FloatField()),
                ('payment_status', models.CharField(max_length=200)),
                ('appointment_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hospitalManage.Appointment')),
            ],
        ),
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('patient_id', models.AutoField(primary_key=True, serialize=False)),
                ('patient_name', models.CharField(max_length=200)),
                ('patient_gender', models.CharField(max_length=200)),
                ('identification', models.CharField(max_length=200)),
                ('phone_number', models.CharField(max_length=200)),
                ('absence', models.IntegerField(default=0)),
                ('address', models.CharField(max_length=200)),
                ('user_id', models.ManyToManyField(to='hospitalManage.User')),
            ],
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('message_id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=200)),
                ('content', models.CharField(max_length=200)),
                ('message_time', models.DateField()),
                ('is_read', models.BooleanField()),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hospitalManage.User')),
            ],
        ),
        migrations.CreateModel(
            name='MedicalRecord',
            fields=[
                ('medical_record_id', models.AutoField(primary_key=True, serialize=False)),
                ('symptom', models.CharField(max_length=200)),
                ('prescription', models.CharField(max_length=200)),
                ('result', models.CharField(max_length=200)),
                ('advice', models.CharField(max_length=200)),
                ('medical_record_date', models.DateField()),
                ('department_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hospitalManage.Department')),
                ('doctor_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hospitalManage.Doctor')),
                ('patient_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hospitalManage.Patient')),
            ],
        ),
        migrations.CreateModel(
            name='Leave',
            fields=[
                ('leave_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('start_time', models.DateTimeField()),
                ('end_time', models.DateTimeField()),
                ('type', models.CharField(max_length=200)),
                ('reseon', models.CharField(max_length=255)),
                ('leave_status', models.CharField(max_length=100)),
                ('doctor_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hospitalManage.Doctor')),
            ],
        ),
        migrations.AddField(
            model_name='appointment',
            name='doctor_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hospitalManage.Doctor'),
        ),
        migrations.AddField(
            model_name='appointment',
            name='patient_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hospitalManage.Patient'),
        ),
    ]
