# Generated by Django 2.2.25 on 2023-05-23 17:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hospitalManage', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Admin',
        ),
        migrations.RemoveField(
            model_name='appointment',
            name='doctor_id',
        ),
        migrations.RemoveField(
            model_name='appointment',
            name='patient_id',
        ),
        migrations.DeleteModel(
            name='CarouselMap',
        ),
        migrations.DeleteModel(
            name='Code',
        ),
        migrations.RemoveField(
            model_name='doctor',
            name='department_id',
        ),
        migrations.RemoveField(
            model_name='leave',
            name='doctor_id',
        ),
        migrations.RemoveField(
            model_name='medicalrecord',
            name='department_id',
        ),
        migrations.RemoveField(
            model_name='medicalrecord',
            name='doctor_id',
        ),
        migrations.RemoveField(
            model_name='medicalrecord',
            name='patient_id',
        ),
        migrations.RemoveField(
            model_name='message',
            name='user_id',
        ),
        migrations.DeleteModel(
            name='News',
        ),
        migrations.DeleteModel(
            name='Notification',
        ),
        migrations.RemoveField(
            model_name='patient',
            name='user_id',
        ),
        migrations.RemoveField(
            model_name='payment',
            name='appointment_id',
        ),
        migrations.RemoveField(
            model_name='schedule',
            name='doctor_id',
        ),
        migrations.RemoveField(
            model_name='vacancy',
            name='doctor_id',
        ),
        migrations.DeleteModel(
            name='Vacancy_setting',
        ),
        migrations.DeleteModel(
            name='Appointment',
        ),
        migrations.DeleteModel(
            name='Department',
        ),
        migrations.DeleteModel(
            name='Doctor',
        ),
        migrations.DeleteModel(
            name='Leave',
        ),
        migrations.DeleteModel(
            name='MedicalRecord',
        ),
        migrations.DeleteModel(
            name='Message',
        ),
        migrations.DeleteModel(
            name='Patient',
        ),
        migrations.DeleteModel(
            name='Payment',
        ),
        migrations.DeleteModel(
            name='Schedule',
        ),
        migrations.DeleteModel(
            name='User',
        ),
        migrations.DeleteModel(
            name='Vacancy',
        ),
    ]
