# Generated by Django 3.2.19 on 2023-06-02 22:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Admin',
            fields=[
                ('admin_image', models.CharField(blank=True, max_length=255)),
                ('admin_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=100)),
                ('password', models.CharField(max_length=100)),
                ('introduction', models.TextField(max_length=100000)),
            ],
        ),
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('appointment_id', models.AutoField(primary_key=True, serialize=False)),
                ('appointment_time', models.DateTimeField()),
                ('appointment_status', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Code',
            fields=[
                ('verification_code', models.CharField(max_length=20)),
                ('phone_number', models.BigIntegerField(primary_key=True, serialize=False)),
                ('create_time', models.DateTimeField()),
                ('expire_time', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Department',
            fields=[
                ('department_id', models.AutoField(primary_key=True, serialize=False)),
                ('department_name', models.CharField(max_length=20)),
                ('department_type', models.CharField(max_length=20)),
                ('department_introduction', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Doctor',
            fields=[
                ('doctor_id', models.AutoField(primary_key=True, serialize=False)),
                ('phone_number', models.CharField(max_length=200)),
                ('doctor_name', models.CharField(max_length=200)),
                ('doctor_gender', models.CharField(max_length=200)),
                ('doctor_image', models.ImageField(blank=True, default='', upload_to='')),
                ('doctor_introduction', models.CharField(max_length=200)),
                ('department_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.department')),
            ],
        ),
        migrations.CreateModel(
            name='News',
            fields=[
                ('news_id', models.AutoField(primary_key=True, serialize=False)),
                ('news_content', models.TextField(max_length=100000)),
                ('short_info', models.CharField(max_length=255)),
                ('news_title', models.CharField(max_length=200)),
                ('news_date', models.DateField()),
                ('type', models.IntegerField(default=0)),
                ('image', models.ImageField(blank=True, upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('notification_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('content', models.TextField(max_length=100000)),
                ('short_info', models.CharField(max_length=255)),
                ('title', models.CharField(max_length=200)),
                ('notification_time', models.DateField()),
                ('type', models.IntegerField(default=0)),
                ('image', models.ImageField(blank=True, upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('user_id', models.AutoField(primary_key=True, serialize=False)),
                ('phone_number', models.CharField(max_length=200)),
                ('passwd', models.CharField(max_length=200)),
                ('avatar', models.ImageField(blank=True, null=True, upload_to='avatars/')),
                ('type', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Vacancy_setting',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('vacancy_cnt', models.IntegerField(default=10)),
                ('vacancy_day', models.IntegerField()),
                ('vacancy_time', models.DecimalField(decimal_places=1, max_digits=3)),
            ],
        ),
        migrations.CreateModel(
            name='Vacancy',
            fields=[
                ('vacancy_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('vacancy_count', models.IntegerField(default=10)),
                ('vacancy_left', models.IntegerField(default=10)),
                ('start_time', models.DateTimeField()),
                ('end_time', models.DateTimeField()),
                ('doctor_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.doctor')),
            ],
        ),
        migrations.CreateModel(
            name='Schedule',
            fields=[
                ('schedule_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('schedule_day', models.IntegerField()),
                ('schedule_is_morning', models.IntegerField(default=0)),
                ('doctor_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.doctor')),
            ],
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('payment_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('amount', models.FloatField()),
                ('payment_status', models.CharField(max_length=200)),
                ('appointment_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.appointment')),
            ],
        ),
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('patient_id', models.AutoField(primary_key=True, serialize=False)),
                ('patient_name', models.CharField(max_length=200)),
                ('patient_gender', models.CharField(max_length=200)),
                ('identification', models.CharField(max_length=200)),
                ('phone_number', models.CharField(blank=True, max_length=200, null=True)),
                ('absence', models.IntegerField(default=0)),
                ('address', models.CharField(blank=True, max_length=200, null=True)),
                ('age', models.IntegerField(default=0)),
                ('user_id', models.ManyToManyField(to='app.User')),
            ],
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('message_id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=200)),
                ('content', models.CharField(max_length=200)),
                ('message_time', models.DateTimeField()),
                ('is_read', models.BooleanField()),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.user')),
            ],
        ),
        migrations.CreateModel(
            name='MedicalRecord',
            fields=[
                ('medical_record_id', models.AutoField(primary_key=True, serialize=False)),
                ('symptom', models.CharField(max_length=200)),
                ('prescription', models.CharField(max_length=200)),
                ('result', models.CharField(max_length=200)),
                ('advice', models.CharField(max_length=200)),
                ('medical_record_date', models.DateField()),
                ('appointment_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.appointment')),
                ('department_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.department')),
                ('doctor_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.doctor')),
                ('patient_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.patient')),
            ],
        ),
        migrations.CreateModel(
            name='Leave',
            fields=[
                ('leave_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('start_time', models.DateTimeField()),
                ('end_time', models.DateTimeField()),
                ('type', models.CharField(max_length=200)),
                ('reseon', models.CharField(max_length=255)),
                ('leave_status', models.CharField(max_length=100)),
                ('doctor_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.doctor')),
            ],
        ),
        migrations.AddField(
            model_name='appointment',
            name='doctor_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.doctor'),
        ),
        migrations.AddField(
            model_name='appointment',
            name='patient_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.patient'),
        ),
    ]
